floriano/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from floriano import views
from django.contrib.sitemaps import Sitemap, FlatPageSitemap
import settings

sitemaps = {
    'site': Sitemap,
    'flatpages': FlatPageSitemap,
    }


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    (r'^$', views.home),
    (r'^contato/$', views.contato),
    (r'^contato/(?P<slug>[\w_-]+)/$', views.contato),


    (r'^noticias/$', 'apps.materias.views.noticias'),
    (r'^noticias/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.materias.views.ver_materia'),
    (r'^noticias/(?P<categoria>[\w_-]+)/', 'apps.materias.views.ver_secretaria'),

    (r'^busca/$', 'apps.materias.views.busca'),

    (r'^albuns/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.multimidia.views.album'),
    (r'^albuns/$', 'apps.multimidia.views.central_albuns'),
    (r'^videos/$', 'apps.multimidia.views.videos'),

    (r'^a-cidade/$', 'apps.cidade.views.cidade'),
    (r'^equipe/$', 'apps.servicos.views.equipe'),
    (r'^servicos/(?P<slug>[\w_-]+)/$', 'apps.servicos.views.servico'),
    (r'^servicos/$', 'apps.servicos.views.servicos'),
    (r'^obras/$', 'apps.servicos.views.obra'),
    (r'^licitacoes/$', 'apps.servicos.views.licitacao'),
    (r'^legislacoes/$', 'apps.legislacao.views.legislacoes'),

    (r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nAllow: /", mimetype="text/plain")),
    (r'^sitemap\.xml$', 'floriano.views.sitemap'),

)

#urlpatterns += patterns('django.contrib.flatpages.views',
#    url(r'^sobre-floriano/$','flatpage', {'url': '/sobre-floriano/'}, name='sobre'),
#    url(r'^principais-eventos/$','flatpage', {'url': '/principais-eventos/'}, name='eventos'),
#    url(r'^generalidades/$','flatpage', {'url': '/generalidades/'}, name='generalidades'),
#    url(r'^educacao-e-economia/$','flatpage', {'url': '/educacao-e-economia/'}, name='economia'),
#)

urlpatterns += patterns('',
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

apps/multimidia/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField

BANNER_CHOICES = (('1', 'Banner Medio 690x118'), ('2', 'Banner Sidebar 210x125'), ('3', 'Banner Topo 450x66'))

class Banner(models.Model):
    titulo=models.CharField(max_length=100)
    arquivo=models.FileField(upload_to='banners')
    status=models.BooleanField(verbose_name='Ativo? ', default=True)
    publicado_em = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)
    posicao=models.CharField('Posicao do banner', max_length=1, choices = BANNER_CHOICES)
    url=models.URLField("Site do banner", blank=True, null=True)
    class Meta:
        verbose_name_plural = "Banners"

    def __unicode__(self):
        return self.titulo

class Album(models.Model):

    titulo = models.CharField(max_length=100, help_text="Titulo do album com até 100 caracteres.")
    foto_destaque = models.ImageField(upload_to='uploads/album/%Y/%m/', help_text="Foto destaque do Album. Dimensões 120x80")
    foto_medium = ImageRatioField('foto_destaque', '270x110')
    foto_big = ImageRatioField('foto_destaque', '390x225')
    foto_small = ImageRatioField('foto_destaque', '160x120')
    slug = models.SlugField(max_length=100, blank=True, unique=True)
    creditos = models.CharField(max_length = 150, blank = True, null = True)

    visualizacoes = models.IntegerField(default=0)
    publicado_em = models.DateTimeField(verbose_name='Data de Publicação', default=datetime.now)
    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', default=datetime.now, blank=True)
    status = models.BooleanField(verbose_name='Ativo? ', default=True)

    class Meta:
        ordering = ('-cadastrado_em',)
        verbose_name = u'Album'
        verbose_name_plural = u'Albuns'

    def imagemAdmin(self):
        if self.foto_destaque:
            im = get_thumbnailer(self.foto_destaque).get_thumbnail({
                'size': (120, 135),
                'box': self.foto_small
            })
            return '<img src="{0}" />'.format(im.url)
        else:
            return 'Sem Imagem'

    imagemAdmin.allow_tags = True
    imagemAdmin.short_description = u'Foto'

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return ('/albuns/%s-%i.html' % (self.slug, self.id))

    def get_medium(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
                    'size': (270,110),
                    'box': self.foto_medium,
                    'crop': True,
                    'detail': True,
                }).url

    def get_big(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
                    'size': (390,225),
                    'box': self.foto_big,
                    'crop': True,
                    'detail': True,
                }).url

    def get_small(self):
        return get_thumbnailer(self.foto_destaque).get_thumbnail({
                    'size': (160, 120),
                    'box': self.foto_small,
                    'crop': True,
                    'detail': True,
                }).url

class Foto(models.Model):

    foto = models.ImageField(upload_to='uploads/')#, size=(530, 397)
    legenda = models.CharField(max_length=200, blank=True)
    foto_thumb = ImageRatioField('foto', '160x120')
    album = models.ForeignKey(Album)
    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', default=datetime.now, blank=True, null = True)
    status = models.BooleanField(verbose_name='Ativo? ', default=True)

    class Meta:
        ordering = ('-cadastrado_em',)

    def imagem(self):
        if self.foto:
            try:
                im = get_thumbnailer(self.foto).get_thumbnail({
                    'size': (135, 90),
                    'box': self.foto_thumb
                })
                return im.url
            except:
                return ''

        return ''

    def imagemAdmin(self):
        if self.foto:
            im = get_thumbnailer(self.foto).get_thumbnail({
                'size': (135, 90),
                'box': self.foto_thumb
            })
            return '<img src="{0}" />'.format(im.url)
        else:
            return 'Sem Imagem'

    def get_foto(self):
        return "/media/%s" % self.foto

    def get_thumb(self):
        return get_thumbnailer(self.foto).get_thumbnail({
                    'size': (160,120),
                    'box': self.foto_thumb,
                    'crop': True,
                    'detail': True,
                }).url

    imagemAdmin.allow_tags = True
    imagemAdmin.short_description = u'Foto'

def album_pre_save(signal, instance, sender, **kwargs):
    """Este signal gera um slug automaticamente. Ele verifica se ja existe um
    artigo com o mesmo slug e acrescenta um numero ao final para evitar
    duplicidade"""
    if not instance.slug:
        slug = slugify(instance.titulo)
        novo_slug = slug
        contador = 0

        while Album.objects.filter(slug=novo_slug).exclude(id=instance.id).count() > 0:
            contador += 1
            novo_slug = '%s-%d'%(slug, contador)

        instance.slug = novo_slug
signals.pre_save.connect(album_pre_save, sender=Album)


class Video(models.Model):
    class Meta:
        ordering = ('-publicado_em',)

    titulo = models.CharField(max_length=100, help_text="Tamanho maximo de 100 caracteres.")
    visualizacoes = models.IntegerField(default=0)
    slug = models.SlugField(max_length=100, blank=True, unique=True)

    foto = models.ImageField(upload_to='uploads/video/%Y/%m/', null = True, blank = True)
    video = models.CharField(max_length=200, help_text="Url do Youtube")
    video_id = models.CharField(max_length=30)

    publicado_em = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now, blank=True, help_text="Data em que este video deve ser publicado.")
    cadastrado_em = models.DateTimeField(verbose_name='Data do Cadastro', default=datetime.now, blank=True)
    status = models.BooleanField(default=True)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return ('/videos/%s-%i.html' % (self.slug, self.id))


def video_pre_save(signal, instance, sender, **kwargs):
    """Este signal gera um slug automaticamente. Ele verifica se ja existe um
    artigo com o mesmo slug e acrescenta um numero ao final para evitar
    duplicidade"""
    novo_slug = None
    if not instance.slug:
        slug = slugify(instance.titulo)
        novo_slug = slug
        contador = 0

        while Video.objects.filter(slug=novo_slug).exclude(id=instance.id).count() > 0:
            contador += 1
            novo_slug = '%s-%d'%(slug, contador)

        instance.slug = novo_slug

signals.pre_save.connect(video_pre_save, sender=Video)

apps/multimidia/views.py
# -*- coding: utf-8 -*-
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.template import RequestContext
from django.shortcuts import render_to_response
from apps.multimidia.models import Album, Video
from django.shortcuts import get_object_or_404
from datetime import datetime


def album(request, slug, id):
    album = get_object_or_404(Album, slug = slug,id=id, status = True)
    albuns = Album.objects.filter(status=True).exclude(pk= album.pk).exclude(publicado_em__gte=datetime.now()).order_by('-publicado_em')[:8]
    try:
        titulo = album.titulo + ' - '
    except:
        titulo = ''

    return render_to_response('floriano/multimidia/fotos.html', locals(),
                              context_instance=RequestContext(request))

def central_albuns(request):
    albuns = Album.objects.filter(status=True).exclude(publicado_em__gte=datetime.now()).order_by('-publicado_em')
    try:
        titulo = 'Álbuns'
    except:
        titulo = ''

    return render_to_response('floriano/multimidia/albuns.html', locals(),
                              context_instance=RequestContext(request))

def videos(request):
    videos = Video.objects.all()
    paginator = Paginator(videos, 4)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        videos = paginator.page(page)
    except (EmptyPage, InvalidPage):
        videos = paginator.page(paginator.num_pages)
    # agenda_passados = Agenda.objects.filter(horario__lte=datetime.now)

    return render_to_response('floriano/multimidia/videos.html', locals(),
        context_instance=RequestContext(request))

floriano/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from apps.destaques.models import Destaque
from apps.materias.models import Materias
from apps.multimidia.models import Video, Album, Banner
from django.core.mail import send_mail
from django.http import HttpResponseRedirect

ASSUNTOS = ('ouvidoria', 'sala-de-imprensa', 'reclamacoes')

def home(request):
    slides = Destaque.objects.filter(posicao=1).order_by('-publicado_em')[:6]
    destaque1 = Destaque.objects.filter(posicao=2).order_by('-publicado_em')[:1]
    destaque2 = Destaque.objects.filter(posicao=3).order_by('-publicado_em')[:1]
    destaque3 = Destaque.objects.filter(posicao=4).order_by('-publicado_em')[:1]
    ultimas = Materias.objects.filter(status=True).order_by('-publicado_em')[:4]
    videos = Video.objects.filter(status=True).order_by('-publicado_em')[:1]
    albuns = Album.objects.filter(status=True).order_by('-publicado_em')[:3]
    banner_medio = Banner.objects.filter(posicao=1, status=True).order_by('-publicado_em')[:1]

    return render_to_response('index.html', locals(), context_instance=RequestContext(request))

def contato(request, slug=''):
    if request.POST:
        form = request.POST
        assunto = form.get('assunto').lower().replace(' ', '-')

        origem = form.get('email')
        mensagem = form.get('comentario') + "\n" + origem + "\n" + form.get('nome')
        if assunto == ASSUNTOS[0]:
            destino = ['ouvidoria@floriano.pi.gov.br']
        elif assunto == ASSUNTOS[1]:
            destino = ['comunicacao@floriano.pi.gov.br']
        elif assunto == ASSUNTOS[2]:
            destino = ['ouvidoria@floriano.pi.gov.br']
        send_mail(assunto, mensagem, origem, recipient_list=destino)
        return HttpResponseRedirect('/')
    else:
        assuntos = ASSUNTOS
        selected = slug
    return render_to_response('floriano/contato.html', locals(), context_instance=RequestContext(request))

def sitemap(request):
    p = request.GET.get('p',1)
    vmin = ((1000 * int(p)) - 1000)
    vmax = 1000 * int(p)

    stmapgr = Materias.objects.filter(status=True).order_by('-id')[vmin:vmax]

    return render_to_response('xml/geral.xml', locals(),
                              context_instance=RequestContext(request))

templates/floriano/multimidia/albuns.html
{% extends 'elements/base.html' %}

{% block extracss %}
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/foundation.min.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/estilo.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/flexslider.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/fancybox.css">
  <script src="{{ MEDIA_URL }}javascripts/modernizr.foundation.js"></script>
{% endblock %}
{% block content %}
      <div class="nine columns">
        <h3 class="label-title"><a href="">Galeria de Albuns</a></h3>
          <div class="panel sobre">
            <div class="row">
              <div class="twelve columns galeriafotos">
                  {% for album in albuns %}
                  <a class="fancybox" rel="gallery1" href="{{ album.get_absolute_url }}" title="{{ album.titulo }}">
                    <img src="{{ album.get_small }}" alt="{{ album.titulo }}" />
                  </a>
                  {% endfor %}
              </div>
            </div>
         </div>
      </div>
{% endblock %}

{% block extrajs %}
  <script src="{{ MEDIA_URL }}javascripts/jquery.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/foundation.min.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/flexslider.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/fancybox.js"></script>

  <!-- Initialize JS Plugins -->
  <script src="{{ MEDIA_URL }}javascripts/app.js"></script>

  <script type="text/javascript">
     $('#main-slider').flexslider({animation: 'fade', controlNav: true, directionNav: true, controlsContainer: '.flex-container', });
  </script>

  <script type="text/javascript">
     $(".fancybox").fancybox({
        openEffect  : 'none',
        closeEffect : 'none'
      });
  </script>
{% endblock %}

templates/floriano/multimidia/fotos.html
{% extends 'elements/base.html' %}

{% block extracss %}
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/foundation.min.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/estilo.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/flexslider.css">
  <link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/fancybox.css">
  <script src="{{ MEDIA_URL }}javascripts/modernizr.foundation.js"></script>
{% endblock %}
{% block content %}
      <div class="nine columns">
        <h3 class="label-title"><a href="{% url 'apps.multimidia.views.central_albuns' %}">Galeria de fotos</a></h3>
          <div class="panel sobre">
            <div class="row">
              <div class="twelve columns galeriafotos">
                <h4>{{ album.titulo }}</h4>
                  {% for foto in album.foto_set.all %}
                  <a class="fancybox" rel="gallery1" href="{{ foto.get_foto }}" title="{{ foto.legenda }}">
                    <img src="{{ foto.get_thumb }}" alt="{{ foto.legenda }}" />
                  </a>
                  {% endfor %}
              </div>
            </div>
         </div>
      <h3 class="label-title"><a href="{% url 'apps.multimidia.views.central_albuns' %}">veja mais galerias</a></h3>
          <div class="panel sobre">
            <div class="row">
              <div class="twelve columns galeriafotos">
                  {% for album in albuns %}
                  <a class="fancybox" rel="gallery1" href="{{ album.get_absolute_url }}" title="{{ album.titulo }}">
                    <img src="{{ album.get_small }}" alt="{{ album.titulo }}" />
                  </a>
                  {% endfor %}
              </div>
            </div>
         </div>
      </div>
{% endblock %}

{% block extrajs %}
  <script src="{{ MEDIA_URL }}javascripts/jquery.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/foundation.min.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/flexslider.js"></script>
  <script src="{{ MEDIA_URL }}javascripts/fancybox.js"></script>

  <!-- Initialize JS Plugins -->
  <script src="{{ MEDIA_URL }}javascripts/app.js"></script>

  <script type="text/javascript">
     $('#main-slider').flexslider({animation: 'fade', controlNav: true, directionNav: true, controlsContainer: '.flex-container', });
  </script>

  <script type="text/javascript">
     $(".fancybox").fancybox({
        openEffect  : 'none',
        closeEffect : 'none'
      });
  </script>
{% endblock %}

templates/floriano/multimidia/videos.html
{% extends "elements/base.html" %}

{% block title %}Videos{% endblock %}

{% block content %}
      <div class="nine columns">
         <h3 class="label-title"><a href="">Galeria de videos</a></h3>
        <div class="row">
         {% for video in videos %}
          <div  class="six columns">
            <div class="item-videos">
              <h3 class="label-title"><a href="">{{ video.titulo }}</a></h3>
               <div class="flex-video">
                 <iframe width="420" height="312" src="http://www.youtube.com/embed/{{ video.video_id }}" frameborder="0" allowfullscreen></iframe>
               </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="row">
            <div class="three columns centered">
                <ul class="pagination">
                    {% if videos.has_previous %}
                        <li class="arrow"><a href="?page={{ videos.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="arrow unavailable">&laquo;</li>
                    {% endif %}
                    {% for num in videos.paginator.page_range %}
                        {% ifequal num videos.number %}
                            <li class="current"><a href="?page={{ num }}">{{ num }}</a></li>
                        {% else %}
                            <li><a href="?page={{ num }}">{{ num }}</a></li>
                        {% endifequal %}
                    {% endfor %}
                    {% if videos.has_next %}
                        <li class="arrow"><a href="?page={{ videos.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="unavailable">&raquo;</li>
                    {% endif %}
                </ul>
            </div>
        </div>

      </div>

{% endblock %}